yarnPath: .yarn/releases/yarn-4.5.1.cjs
pnpMode: "strict"
# enableGlobalCache: false  # vite dev fails to load global cache. https://github.com/vitejs/vite/issues/15496
nodeLinker: node-modules  # F**k you, electron!
